name: CI
on: [push, pull_request]
jobs:
  tests:
    strategy:
      matrix:
        ruby-version:
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"
        rails-version:
          - "7.0"
          - "7.1"
          - "7.2"
          - "8.0"
          - "8.1"
        exclude:
          - ruby-version: "3.1"
            rails-version: "8.0"
          - ruby-version: "3.1"
            rails-version: "8.1"
      fail-fast: false
    env:
      BUNDLE_GEMFILE: gemfiles/Gemfile.rails-${{ matrix.rails-version }}

    name: ${{ format('Tests (Ruby {0}) (Rails {1})', matrix.ruby-version, matrix.rails-version) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install ddtest
        run: |
          curl -fsSL https://github.com/DataDog/ddtest/releases/latest/download/ddtest-linux-amd64 -o bin/ddtest
          chmod +x bin/ddtest

      - name: Configure Datadog Test Optimization
        uses: datadog/test-visibility-github-action@v3
        with:
          languages: ruby
          api_key: ${{ secrets.DD_API_KEY }}
          site: datadoghq.com

      - name: Run tests
        run: |
          rm -rf .testoptimization
          bin/ddtest run --platform ruby --framework minitest --min-parallelism 1 --max-parallelism 4 --command "bin/test"
